"""
handbook.py - the educational backbone.

A single structured source for every metric/indicator/concept. Powers the
Handbook page AND keeps explanations consistent across the whole app.

Each concept: name, category, definition, formula, interpretation, good, bad,
higher_better (True/False/None), mistakes, limitations.
"""

from __future__ import annotations

CONCEPTS = {
    # ---------------- Valuation ----------------
    "pe": dict(name="P/E (Price / Earnings)", category="Valuation",
        definition="What you pay for each $1 of annual profit.",
        formula="Price ÷ Earnings per share",
        interpretation="Lower can mean cheaper, but a low P/E on a shrinking business is a value trap.",
        good="Context-dependent; ~10-20 for mature firms", bad="Negative (no profit) or extreme vs peers",
        higher_better=False,
        mistakes="Comparing P/E across different industries; ignoring growth.",
        limitations="Meaningless when earnings are negative or one-off."),
    "forward_pe": dict(name="Forward P/E", category="Valuation",
        definition="P/E using next-12-months expected earnings instead of past.",
        formula="Price ÷ expected forward EPS",
        interpretation="Lower than trailing P/E implies earnings are expected to grow.",
        good="Below trailing P/E for a grower", bad="Far above trailing P/E",
        higher_better=False,
        mistakes="Trusting analyst estimates as fact.",
        limitations="Only as good as the forecast behind it."),
    "peg": dict(name="PEG Ratio", category="Valuation",
        definition="P/E adjusted for growth — lets you compare fast and slow growers fairly.",
        formula="P/E ÷ annual EPS growth %",
        interpretation="Around 1 is 'fairly priced for its growth'; under 1 may be cheap.",
        good="< 1", bad="> 2", higher_better=False,
        mistakes="Using an unstable or negative growth rate.",
        limitations="Breaks down for no-growth or erratic-growth firms."),
    "ev_ebitda": dict(name="EV / EBITDA", category="Valuation",
        definition="Whole-company value vs core operating earnings; neutral to debt and tax.",
        formula="Enterprise Value ÷ EBITDA  (EV = market cap + debt − cash)",
        interpretation="The metric pros use to compare firms with different debt loads.",
        good="< 10-12 for many sectors", bad="> 20-25", higher_better=False,
        mistakes="Comparing across capital-intensity differences.",
        limitations="EBITDA ignores real capital spending."),
    "p_fcf": dict(name="Price / Free Cash Flow", category="Valuation",
        definition="Price vs the actual cash a business throws off.",
        formula="Market cap ÷ Free cash flow",
        interpretation="Cash is harder to fake than earnings; lower = more cash per $ paid.",
        good="< 15-20", bad="Negative FCF", higher_better=False,
        mistakes="Ignoring lumpy capex years.",
        limitations="FCF swings with investment cycles."),
    "pb": dict(name="Price / Book", category="Valuation",
        definition="Price vs accounting net worth.",
        formula="Price ÷ Book value per share",
        interpretation="Matters most for banks and asset-heavy firms; weak for asset-light tech.",
        good="~1-3 (sector-dependent)", bad="Very high for an asset-light firm",
        higher_better=False, mistakes="Applying it to software companies.",
        limitations="Book value understates intangibles like brands."),
    # ---------------- Quality ----------------
    "roic": dict(name="ROIC (Return on Invested Capital)", category="Quality",
        definition="Profit earned per $1 of ALL capital (debt + equity). The best single quality gauge.",
        formula="NOPAT ÷ Invested capital",
        interpretation="Above the cost of capital (~8-10%) means the business creates value.",
        good="> 10-15%", bad="< cost of capital", higher_better=True,
        mistakes="Confusing it with ROE (which ignores debt).",
        limitations="Needs full statements; hard to compute cleanly."),
    "roe": dict(name="ROE (Return on Equity)", category="Quality",
        definition="Profit per $1 of shareholder money.",
        formula="Net income ÷ Shareholders' equity",
        interpretation="High is good, but high ROE built on debt is a red flag — read with leverage.",
        good="> 15%", bad="< 0 or inflated by debt", higher_better=True,
        mistakes="Ignoring the debt behind a high number.",
        limitations="Distorted by buybacks and leverage."),
    "gross_margin": dict(name="Gross Margin", category="Quality",
        definition="Revenue left after the direct cost of making the product.",
        formula="(Revenue − COGS) ÷ Revenue",
        interpretation="High and STABLE margins signal pricing power / a moat.",
        good="High and steady for the sector", bad="Falling over time",
        higher_better=True, mistakes="Comparing across unlike industries.",
        limitations="Sector-relative, not absolute."),
    "operating_margin": dict(name="Operating Margin", category="Quality",
        definition="Profit after running costs, before interest and tax.",
        formula="Operating income ÷ Revenue",
        interpretation="Core operational efficiency.",
        good="Rising over time", bad="Negative or shrinking", higher_better=True,
        mistakes="Ignoring one-off charges.",
        limitations="Affected by accounting choices."),
    "debt_to_equity": dict(name="Debt / Equity", category="Quality / Risk",
        definition="Borrowed money vs shareholder money — how leveraged the firm is.",
        formula="Total debt ÷ Shareholders' equity",
        interpretation="Higher = more risk in a downturn. Acceptable levels vary by sector.",
        good="< 1 for most non-financials", bad="> 2-3", higher_better=False,
        mistakes="Comparing a bank's to a software firm's.",
        limitations="Doesn't capture debt maturity or rates."),
    "fcf_growth": dict(name="Free Cash Flow Growth", category="Quality / Growth",
        definition="How fast the real cash generated is growing.",
        formula="(FCF_this − FCF_prior) ÷ FCF_prior",
        interpretation="Sustained FCF growth is a hallmark of compounding businesses.",
        good="Positive and consistent", bad="Declining or erratic", higher_better=True,
        mistakes="Reading a single year as a trend.",
        limitations="Lumpy capex distorts year-to-year."),
    "revenue_growth": dict(name="Revenue Growth", category="Growth",
        definition="How fast sales are growing year over year.",
        formula="(Rev_this − Rev_prior) ÷ Rev_prior",
        interpretation="Consistency beats one big year.",
        good="Steady positive", bad="Negative / decelerating", higher_better=True,
        mistakes="Ignoring whether growth is profitable.",
        limitations="Top-line growth can mask shrinking margins."),
    # ---------------- Portfolio & risk ----------------
    "cagr": dict(name="CAGR (Compound Annual Growth Rate)", category="Portfolio",
        definition="The smoothed annual rate that turns the start value into the end value.",
        formula="(End ÷ Start)^(1 ÷ years) − 1",
        interpretation="The honest single-number 'per year' return over a period.",
        good="Beats a relevant benchmark", bad="Below inflation", higher_better=True,
        mistakes="Treating it as a steady yearly return (real years swing).",
        limitations="Hides the volatility of the path taken."),
    "sharpe": dict(name="Sharpe Ratio", category="Portfolio",
        definition="Return earned per unit of total risk (volatility).",
        formula="(Return − Risk-free rate) ÷ Std dev of returns",
        interpretation="Higher = more reward for the bumpiness endured.",
        good="> 1 is solid, > 2 is excellent", bad="< 0", higher_better=True,
        mistakes="Comparing Sharpe across very different periods.",
        limitations="Penalises upside volatility too (see Sortino)."),
    "sortino": dict(name="Sortino Ratio", category="Portfolio",
        definition="Like Sharpe, but only counts DOWNSIDE volatility as risk.",
        formula="(Return − Risk-free) ÷ Downside deviation",
        interpretation="Fairer than Sharpe for strategies with big upside swings.",
        good="> 1.5", bad="< 0", higher_better=True,
        mistakes="Ignoring how the downside threshold was set.",
        limitations="Needs enough downside data to be stable."),
    "beta": dict(name="Beta", category="Portfolio / Risk",
        definition="How much a stock moves relative to the whole market.",
        formula="Covariance(stock, market) ÷ Variance(market)",
        interpretation="1 = moves with the market; >1 swings more; <1 calmer.",
        good="Match it to your risk tolerance", bad="High beta for a conservative investor",
        higher_better=None, mistakes="Treating beta as total risk.",
        limitations="Backward-looking and unstable over time."),
    "volatility": dict(name="Volatility", category="Portfolio / Risk",
        definition="How much returns bounce around — the standard 'risk' number.",
        formula="Annualised standard deviation of returns",
        interpretation="Higher means a rougher ride, not necessarily worse returns.",
        good="In line with your tolerance", bad="Higher than you can stomach",
        higher_better=False, mistakes="Equating volatility with permanent loss.",
        limitations="Symmetric — treats gains and losses alike."),
    "max_drawdown": dict(name="Max Drawdown", category="Portfolio / Risk",
        definition="The worst peak-to-trough fall over a period.",
        formula="(Trough − Peak) ÷ Peak (most negative)",
        interpretation="The gut-check: could you hold through this drop?",
        good="Smaller", bad="Larger than your drawdown tolerance", higher_better=False,
        mistakes="Forgetting it can recur and be exceeded.",
        limitations="Past worst case isn't the future worst case."),
    "margin_of_safety": dict(name="Margin of Safety", category="Valuation / Risk",
        definition="The discount of price below your estimate of fair value — your cushion for being wrong.",
        formula="(Intrinsic value − Price) ÷ Intrinsic value",
        interpretation="Bigger cushion = more room for error in your assumptions.",
        good="> 20-30%", bad="Negative (paying above value)", higher_better=True,
        mistakes="Trusting a precise-looking intrinsic value.",
        limitations="Only as good as the valuation behind it."),
    "concentration": dict(name="Concentration Risk", category="Risk",
        definition="How much of your portfolio rides on a few names, sectors, or themes.",
        formula="e.g. % in top holding, or sum of squared weights (Herfindahl)",
        interpretation="High concentration = high single-point-of-failure risk.",
        good="Diversified across uncorrelated bets", bad="Most eggs in one basket",
        higher_better=False, mistakes="Owning 8 AI stocks and calling it diversified.",
        limitations="Counts positions, not hidden correlations (see below)."),
    "correlation": dict(name="Correlation", category="Risk",
        definition="How similarly two holdings move together.",
        formula="−1 (opposite) … 0 (unrelated) … +1 (move identically)",
        interpretation="High correlation between holdings means less real diversification.",
        good="Mix of low/negative correlations", bad="Everything moving as one",
        higher_better=None, mistakes="Assuming different tickers = diversified.",
        limitations="Correlations spike toward 1 in a crash."),
    # ---------------- Technical indicators ----------------
    "rsi": dict(name="RSI (Relative Strength Index)", category="Technical",
        definition="Momentum gauge of how fast/much price has risen vs fallen recently.",
        formula="100 − 100 ÷ (1 + avg gain ÷ avg loss), over 14 periods",
        interpretation="Above 70 = potentially overbought; below 30 = potentially oversold.",
        good="Used as ONE input among many", bad="Used as a standalone buy/sell trigger",
        higher_better=None, mistakes="Shorting just because RSI > 70 — it can stay high in strong trends.",
        limitations="Whipsaws in choppy markets; not predictive alone."),
    "macd": dict(name="MACD", category="Technical",
        definition="Trend + momentum from the gap between two moving averages.",
        formula="MACD = EMA(12) − EMA(26); Signal = EMA(9) of MACD",
        interpretation="MACD crossing above its signal line = bullish momentum; below = bearish.",
        good="Confirming an existing trend", bad="Relied on in a sideways market",
        higher_better=None, mistakes="Acting on every crossover.",
        limitations="Lagging — it follows price, doesn't lead it."),
    "stochastic": dict(name="Stochastic Oscillator", category="Technical",
        definition="Where price sits within its recent high-low range.",
        formula="%K = (Close − Low_n) ÷ (High_n − Low_n) × 100",
        interpretation="Above 80 overbought, below 20 oversold.",
        good="In ranging markets", bad="In strong trends (stays pinned)",
        higher_better=None, mistakes="Ignoring the prevailing trend.",
        limitations="Frequent false signals when trending."),
    "williams_r": dict(name="Williams %R", category="Technical",
        definition="Inverse-scaled cousin of the stochastic; overbought/oversold gauge.",
        formula="(High_n − Close) ÷ (High_n − Low_n) × −100",
        interpretation="−20 to 0 overbought; −100 to −80 oversold.",
        good="Spotting exhaustion in a range", bad="As a lone trigger",
        higher_better=None, mistakes="Forgetting the negative scale.",
        limitations="Same trend-blindness as the stochastic."),
    "momentum": dict(name="Momentum", category="Technical",
        definition="Speed of price change over a lookback window.",
        formula="Close − Close_n periods ago",
        interpretation="Positive = strengthening; negative = weakening.",
        good="Confirming trend strength", bad="At trend turning points",
        higher_better=None, mistakes="Chasing after momentum has peaked.",
        limitations="Says nothing about value."),
    "bollinger": dict(name="Bollinger Bands", category="Technical",
        definition="A moving average with volatility-based bands above and below.",
        formula="20-period SMA ± 2 × standard deviation",
        interpretation="Price near the upper band = stretched; bands widen as volatility rises.",
        good="Gauging volatility and range", bad="As a guaranteed reversal signal",
        higher_better=None, mistakes="Assuming touching a band means reversal.",
        limitations="Price can 'walk the band' in strong trends."),
}

CATEGORIES = ["Valuation", "Quality", "Quality / Risk", "Quality / Growth",
              "Growth", "Portfolio", "Portfolio / Risk", "Valuation / Risk",
              "Risk", "Technical"]


def get(concept_id: str) -> dict | None:
    return CONCEPTS.get(concept_id)


def by_category(category: str) -> list[dict]:
    return [dict(id=k, **v) for k, v in CONCEPTS.items() if v["category"] == category]